[workspace]
resolver = "2"
members = [
    "packages/isar_core",
    "packages/isar_core_ffi",
    "packages/mdbx_sys"
]

[patch.crates-io]
cbindgen = { version = "0.71.1" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"