include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    cascade_invocations: ignore
    avoid_positional_boolean_parameters: ignore
    parameter_assignments: ignore
    public_member_api_docs: ignore
    use_string_buffers: ignore
    avoid_equals_and_hash_code_on_mutable_classes: ignore
    hash_and_equals: ignore
    type_annotate_public_apis: ignore
