// ignore_for_file: camel_case_types, non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class IsarCoreBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  IsarCoreBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  IsarCoreBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  ffi.Pointer<ffi.Uint32> isar_find_word_boundaries(
    ffi.Pointer<ffi.Uint8> input_bytes,
    int length,
    ffi.Pointer<ffi.Uint32> number_words,
  ) {
    return _isar_find_word_boundaries(
      input_bytes,
      length,
      number_words,
    );
  }

  late final _isar_find_word_boundaries_ptr =
      _lookup<ffi.NativeFunction<_c_isar_find_word_boundaries>>(
          'isar_find_word_boundaries');
  late final _dart_isar_find_word_boundaries _isar_find_word_boundaries =
      _isar_find_word_boundaries_ptr
          .asFunction<_dart_isar_find_word_boundaries>();

  void isar_free_word_boundaries(
    ffi.Pointer<ffi.Uint32> boundaries,
    int word_count,
  ) {
    return _isar_free_word_boundaries(
      boundaries,
      word_count,
    );
  }

  late final _isar_free_word_boundaries_ptr =
      _lookup<ffi.NativeFunction<_c_isar_free_word_boundaries>>(
          'isar_free_word_boundaries');
  late final _dart_isar_free_word_boundaries _isar_free_word_boundaries =
      _isar_free_word_boundaries_ptr
          .asFunction<_dart_isar_free_word_boundaries>();

  ffi.Pointer<ffi.Int8> isar_get_error(
    int err_code,
  ) {
    return _isar_get_error(
      err_code,
    );
  }

  late final _isar_get_error_ptr =
      _lookup<ffi.NativeFunction<_c_isar_get_error>>('isar_get_error');
  late final _dart_isar_get_error _isar_get_error =
      _isar_get_error_ptr.asFunction<_dart_isar_get_error>();

  void isar_free_error(
    ffi.Pointer<ffi.Int8> error,
  ) {
    return _isar_free_error(
      error,
    );
  }

  late final _isar_free_error_ptr =
      _lookup<ffi.NativeFunction<_c_isar_free_error>>('isar_free_error');
  late final _dart_isar_free_error _isar_free_error =
      _isar_free_error_ptr.asFunction<_dart_isar_free_error>();

  int isar_get(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObject> object,
  ) {
    return _isar_get(
      collection,
      txn,
      object,
    );
  }

  late final _isar_get_ptr =
      _lookup<ffi.NativeFunction<_c_isar_get>>('isar_get');
  late final _dart_isar_get _isar_get =
      _isar_get_ptr.asFunction<_dart_isar_get>();

  int isar_get_by_index(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int index_id,
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<RawObject> object,
  ) {
    return _isar_get_by_index(
      collection,
      txn,
      index_id,
      key,
      object,
    );
  }

  late final _isar_get_by_index_ptr =
      _lookup<ffi.NativeFunction<_c_isar_get_by_index>>('isar_get_by_index');
  late final _dart_isar_get_by_index _isar_get_by_index =
      _isar_get_by_index_ptr.asFunction<_dart_isar_get_by_index>();

  int isar_get_all(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObjectSet> objects,
  ) {
    return _isar_get_all(
      collection,
      txn,
      objects,
    );
  }

  late final _isar_get_all_ptr =
      _lookup<ffi.NativeFunction<_c_isar_get_all>>('isar_get_all');
  late final _dart_isar_get_all _isar_get_all =
      _isar_get_all_ptr.asFunction<_dart_isar_get_all>();

  int isar_get_all_by_index(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int index_id,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> keys,
    ffi.Pointer<RawObjectSet> objects,
  ) {
    return _isar_get_all_by_index(
      collection,
      txn,
      index_id,
      keys,
      objects,
    );
  }

  late final _isar_get_all_by_index_ptr =
      _lookup<ffi.NativeFunction<_c_isar_get_all_by_index>>(
          'isar_get_all_by_index');
  late final _dart_isar_get_all_by_index _isar_get_all_by_index =
      _isar_get_all_by_index_ptr.asFunction<_dart_isar_get_all_by_index>();

  int isar_put(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObject> object,
    bool replace_on_conflict,
  ) {
    return _isar_put(
      collection,
      txn,
      object,
      replace_on_conflict ? 1 : 0,
    );
  }

  late final _isar_put_ptr =
      _lookup<ffi.NativeFunction<_c_isar_put>>('isar_put');
  late final _dart_isar_put _isar_put =
      _isar_put_ptr.asFunction<_dart_isar_put>();

  int isar_put_all(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObjectSet> objects,
    bool replace_on_conflict,
  ) {
    return _isar_put_all(
      collection,
      txn,
      objects,
      replace_on_conflict ? 1 : 0,
    );
  }

  late final _isar_put_all_ptr =
      _lookup<ffi.NativeFunction<_c_isar_put_all>>('isar_put_all');
  late final _dart_isar_put_all _isar_put_all =
      _isar_put_all_ptr.asFunction<_dart_isar_put_all>();

  int isar_delete(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int id,
    ffi.Pointer<ffi.Uint8> deleted,
  ) {
    return _isar_delete(
      collection,
      txn,
      id,
      deleted,
    );
  }

  late final _isar_delete_ptr =
      _lookup<ffi.NativeFunction<_c_isar_delete>>('isar_delete');
  late final _dart_isar_delete _isar_delete =
      _isar_delete_ptr.asFunction<_dart_isar_delete>();

  int isar_delete_by_index(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int index_id,
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<ffi.Uint8> deleted,
  ) {
    return _isar_delete_by_index(
      collection,
      txn,
      index_id,
      key,
      deleted,
    );
  }

  late final _isar_delete_by_index_ptr =
      _lookup<ffi.NativeFunction<_c_isar_delete_by_index>>(
          'isar_delete_by_index');
  late final _dart_isar_delete_by_index _isar_delete_by_index =
      _isar_delete_by_index_ptr.asFunction<_dart_isar_delete_by_index>();

  int isar_delete_all(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<ffi.Int64> ids,
    int ids_length,
    ffi.Pointer<ffi.Uint32> count,
  ) {
    return _isar_delete_all(
      collection,
      txn,
      ids,
      ids_length,
      count,
    );
  }

  late final _isar_delete_all_ptr =
      _lookup<ffi.NativeFunction<_c_isar_delete_all>>('isar_delete_all');
  late final _dart_isar_delete_all _isar_delete_all =
      _isar_delete_all_ptr.asFunction<_dart_isar_delete_all>();

  int isar_delete_all_by_index(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int index_id,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> keys,
    int keys_length,
    ffi.Pointer<ffi.Uint32> count,
  ) {
    return _isar_delete_all_by_index(
      collection,
      txn,
      index_id,
      keys,
      keys_length,
      count,
    );
  }

  late final _isar_delete_all_by_index_ptr =
      _lookup<ffi.NativeFunction<_c_isar_delete_all_by_index>>(
          'isar_delete_all_by_index');
  late final _dart_isar_delete_all_by_index _isar_delete_all_by_index =
      _isar_delete_all_by_index_ptr
          .asFunction<_dart_isar_delete_all_by_index>();

  int isar_clear(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
  ) {
    return _isar_clear(
      collection,
      txn,
    );
  }

  late final _isar_clear_ptr =
      _lookup<ffi.NativeFunction<_c_isar_clear>>('isar_clear');
  late final _dart_isar_clear _isar_clear =
      _isar_clear_ptr.asFunction<_dart_isar_clear>();

  int isar_json_import(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<ffi.Int8> id_name,
    ffi.Pointer<ffi.Uint8> json_bytes,
    int json_length,
    bool replace_on_conflict,
  ) {
    return _isar_json_import(
      collection,
      txn,
      id_name,
      json_bytes,
      json_length,
      replace_on_conflict ? 1 : 0,
    );
  }

  late final _isar_json_import_ptr =
      _lookup<ffi.NativeFunction<_c_isar_json_import>>('isar_json_import');
  late final _dart_isar_json_import _isar_json_import =
      _isar_json_import_ptr.asFunction<_dart_isar_json_import>();

  void isar_connect_dart_api(
    ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> ptr,
  ) {
    return _isar_connect_dart_api(
      ptr,
    );
  }

  late final _isar_connect_dart_api_ptr =
      _lookup<ffi.NativeFunction<_c_isar_connect_dart_api>>(
          'isar_connect_dart_api');
  late final _dart_isar_connect_dart_api _isar_connect_dart_api =
      _isar_connect_dart_api_ptr.asFunction<_dart_isar_connect_dart_api>();

  void isar_filter_static(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    bool value,
  ) {
    return _isar_filter_static(
      filter,
      value ? 1 : 0,
    );
  }

  late final _isar_filter_static_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_static>>('isar_filter_static');
  late final _dart_isar_filter_static _isar_filter_static =
      _isar_filter_static_ptr.asFunction<_dart_isar_filter_static>();

  void isar_filter_and_or(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    bool and,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> conditions,
    int length,
  ) {
    return _isar_filter_and_or(
      filter,
      and ? 1 : 0,
      conditions,
      length,
    );
  }

  late final _isar_filter_and_or_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_and_or>>('isar_filter_and_or');
  late final _dart_isar_filter_and_or _isar_filter_and_or =
      _isar_filter_and_or_ptr.asFunction<_dart_isar_filter_and_or>();

  void isar_filter_not(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    ffi.Pointer<ffi.NativeType> condition,
  ) {
    return _isar_filter_not(
      filter,
      condition,
    );
  }

  late final _isar_filter_not_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_not>>('isar_filter_not');
  late final _dart_isar_filter_not _isar_filter_not =
      _isar_filter_not_ptr.asFunction<_dart_isar_filter_not>();

  int isar_filter_link(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    ffi.Pointer<ffi.NativeType> condition,
    int link_id,
  ) {
    return _isar_filter_link(
      collection,
      filter,
      condition,
      link_id,
    );
  }

  late final _isar_filter_link_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_link>>('isar_filter_link');
  late final _dart_isar_filter_link _isar_filter_link =
      _isar_filter_link_ptr.asFunction<_dart_isar_filter_link>();

  int isar_filter_null(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int property_id,
    bool any_null,
  ) {
    return _isar_filter_null(
      collection,
      filter,
      property_id,
      any_null ? 1 : 0,
    );
  }

  late final _isar_filter_null_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_null>>('isar_filter_null');
  late final _dart_isar_filter_null _isar_filter_null =
      _isar_filter_null_ptr.asFunction<_dart_isar_filter_null>();

  int isar_filter_id(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int lower,
    bool include_lower,
    int upper,
    bool include_upper,
  ) {
    return _isar_filter_id(
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
    );
  }

  late final _isar_filter_id_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_id>>('isar_filter_id');
  late final _dart_isar_filter_id _isar_filter_id =
      _isar_filter_id_ptr.asFunction<_dart_isar_filter_id>();

  int isar_filter_byte(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int lower,
    bool include_lower,
    int upper,
    bool include_upper,
    int property_id,
  ) {
    return _isar_filter_byte(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      property_id,
    );
  }

  late final _isar_filter_byte_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_byte>>('isar_filter_byte');
  late final _dart_isar_filter_byte _isar_filter_byte =
      _isar_filter_byte_ptr.asFunction<_dart_isar_filter_byte>();

  int isar_filter_long(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int lower,
    bool include_lower,
    int upper,
    bool include_upper,
    int property_id,
  ) {
    return _isar_filter_long(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      property_id,
    );
  }

  late final _isar_filter_long_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_long>>('isar_filter_long');
  late final _dart_isar_filter_long _isar_filter_long =
      _isar_filter_long_ptr.asFunction<_dart_isar_filter_long>();

  int isar_filter_double(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    double lower,
    double upper,
    int property_id,
  ) {
    return _isar_filter_double(
      collection,
      filter,
      lower,
      upper,
      property_id,
    );
  }

  late final _isar_filter_double_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_double>>('isar_filter_double');
  late final _dart_isar_filter_double _isar_filter_double =
      _isar_filter_double_ptr.asFunction<_dart_isar_filter_double>();

  int isar_filter_string(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    ffi.Pointer<ffi.Int8> lower,
    bool include_lower,
    ffi.Pointer<ffi.Int8> upper,
    bool include_upper,
    bool case_sensitive,
    int property_id,
  ) {
    return _isar_filter_string(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      case_sensitive ? 1 : 0,
      property_id,
    );
  }

  late final _isar_filter_string_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_string>>('isar_filter_string');
  late final _dart_isar_filter_string _isar_filter_string =
      _isar_filter_string_ptr.asFunction<_dart_isar_filter_string>();

  int isar_filter_string_starts_with(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    ffi.Pointer<ffi.Int8> value,
    bool case_sensitive,
    int property_id,
  ) {
    return _isar_filter_string_starts_with(
      collection,
      filter,
      value,
      case_sensitive ? 1 : 0,
      property_id,
    );
  }

  late final _isar_filter_string_starts_with_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_string_starts_with>>(
          'isar_filter_string_starts_with');
  late final _dart_isar_filter_string_starts_with
      _isar_filter_string_starts_with = _isar_filter_string_starts_with_ptr
          .asFunction<_dart_isar_filter_string_starts_with>();

  int isar_filter_string_ends_with(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    ffi.Pointer<ffi.Int8> value,
    bool case_sensitive,
    int property_id,
  ) {
    return _isar_filter_string_ends_with(
      collection,
      filter,
      value,
      case_sensitive ? 1 : 0,
      property_id,
    );
  }

  late final _isar_filter_string_ends_with_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_string_ends_with>>(
          'isar_filter_string_ends_with');
  late final _dart_isar_filter_string_ends_with _isar_filter_string_ends_with =
      _isar_filter_string_ends_with_ptr
          .asFunction<_dart_isar_filter_string_ends_with>();

  int isar_filter_string_contains(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    ffi.Pointer<ffi.Int8> value,
    bool case_sensitive,
    int property_id,
  ) {
    return _isar_filter_string_contains(
      collection,
      filter,
      value,
      case_sensitive ? 1 : 0,
      property_id,
    );
  }

  late final _isar_filter_string_contains_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_string_contains>>(
          'isar_filter_string_contains');
  late final _dart_isar_filter_string_contains _isar_filter_string_contains =
      _isar_filter_string_contains_ptr
          .asFunction<_dart_isar_filter_string_contains>();

  int isar_filter_string_matches(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    ffi.Pointer<ffi.Int8> value,
    bool case_sensitive,
    int property_id,
  ) {
    return _isar_filter_string_matches(
      collection,
      filter,
      value,
      case_sensitive ? 1 : 0,
      property_id,
    );
  }

  late final _isar_filter_string_matches_ptr =
      _lookup<ffi.NativeFunction<_c_isar_filter_string_matches>>(
          'isar_filter_string_matches');
  late final _dart_isar_filter_string_matches _isar_filter_string_matches =
      _isar_filter_string_matches_ptr
          .asFunction<_dart_isar_filter_string_matches>();

  void isar_key_create(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> key,
  ) {
    return _isar_key_create(
      key,
    );
  }

  late final _isar_key_create_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_create>>('isar_key_create');
  late final _dart_isar_key_create _isar_key_create =
      _isar_key_create_ptr.asFunction<_dart_isar_key_create>();

  void isar_key_add_byte(
    ffi.Pointer<ffi.NativeType> key,
    int value,
  ) {
    return _isar_key_add_byte(
      key,
      value,
    );
  }

  late final _isar_key_add_byte_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_byte>>('isar_key_add_byte');
  late final _dart_isar_key_add_byte _isar_key_add_byte =
      _isar_key_add_byte_ptr.asFunction<_dart_isar_key_add_byte>();

  void isar_key_add_int(
    ffi.Pointer<ffi.NativeType> key,
    int value,
  ) {
    return _isar_key_add_int(
      key,
      value,
    );
  }

  late final _isar_key_add_int_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_int>>('isar_key_add_int');
  late final _dart_isar_key_add_int _isar_key_add_int =
      _isar_key_add_int_ptr.asFunction<_dart_isar_key_add_int>();

  void isar_key_add_long(
    ffi.Pointer<ffi.NativeType> key,
    int value,
  ) {
    return _isar_key_add_long(
      key,
      value,
    );
  }

  late final _isar_key_add_long_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_long>>('isar_key_add_long');
  late final _dart_isar_key_add_long _isar_key_add_long =
      _isar_key_add_long_ptr.asFunction<_dart_isar_key_add_long>();

  void isar_key_add_float(
    ffi.Pointer<ffi.NativeType> key,
    double value,
  ) {
    return _isar_key_add_float(
      key,
      value,
    );
  }

  late final _isar_key_add_float_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_float>>('isar_key_add_float');
  late final _dart_isar_key_add_float _isar_key_add_float =
      _isar_key_add_float_ptr.asFunction<_dart_isar_key_add_float>();

  void isar_key_add_double(
    ffi.Pointer<ffi.NativeType> key,
    double value,
  ) {
    return _isar_key_add_double(
      key,
      value,
    );
  }

  late final _isar_key_add_double_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_double>>(
          'isar_key_add_double');
  late final _dart_isar_key_add_double _isar_key_add_double =
      _isar_key_add_double_ptr.asFunction<_dart_isar_key_add_double>();

  void isar_key_add_string(
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<ffi.Int8> value,
    bool case_sensitive,
  ) {
    return _isar_key_add_string(
      key,
      value,
      case_sensitive ? 1 : 0,
    );
  }

  late final _isar_key_add_string_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_string>>(
          'isar_key_add_string');
  late final _dart_isar_key_add_string _isar_key_add_string =
      _isar_key_add_string_ptr.asFunction<_dart_isar_key_add_string>();

  void isar_key_add_string_hash(
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<ffi.Int8> value,
    bool case_sensitive,
  ) {
    return _isar_key_add_string_hash(
      key,
      value,
      case_sensitive ? 1 : 0,
    );
  }

  late final _isar_key_add_string_hash_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_string_hash>>(
          'isar_key_add_string_hash');
  late final _dart_isar_key_add_string_hash _isar_key_add_string_hash =
      _isar_key_add_string_hash_ptr
          .asFunction<_dart_isar_key_add_string_hash>();

  void isar_key_add_string_list_hash(
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> value,
    int length,
    bool case_sensitive,
  ) {
    return _isar_key_add_string_list_hash(
      key,
      value,
      length,
      case_sensitive ? 1 : 0,
    );
  }

  late final _isar_key_add_string_list_hash_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_string_list_hash>>(
          'isar_key_add_string_list_hash');
  late final _dart_isar_key_add_string_list_hash
      _isar_key_add_string_list_hash = _isar_key_add_string_list_hash_ptr
          .asFunction<_dart_isar_key_add_string_list_hash>();

  void isar_key_add_byte_list_hash(
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<ffi.Uint8> value,
    int length,
  ) {
    return _isar_key_add_byte_list_hash(
      key,
      value,
      length,
    );
  }

  late final _isar_key_add_byte_list_hash_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_byte_list_hash>>(
          'isar_key_add_byte_list_hash');
  late final _dart_isar_key_add_byte_list_hash _isar_key_add_byte_list_hash =
      _isar_key_add_byte_list_hash_ptr
          .asFunction<_dart_isar_key_add_byte_list_hash>();

  void isar_key_add_int_list_hash(
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<ffi.Int32> value,
    int length,
  ) {
    return _isar_key_add_int_list_hash(
      key,
      value,
      length,
    );
  }

  late final _isar_key_add_int_list_hash_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_int_list_hash>>(
          'isar_key_add_int_list_hash');
  late final _dart_isar_key_add_int_list_hash _isar_key_add_int_list_hash =
      _isar_key_add_int_list_hash_ptr
          .asFunction<_dart_isar_key_add_int_list_hash>();

  void isar_key_add_long_list_hash(
    ffi.Pointer<ffi.NativeType> key,
    ffi.Pointer<ffi.Int64> value,
    int length,
  ) {
    return _isar_key_add_long_list_hash(
      key,
      value,
      length,
    );
  }

  late final _isar_key_add_long_list_hash_ptr =
      _lookup<ffi.NativeFunction<_c_isar_key_add_long_list_hash>>(
          'isar_key_add_long_list_hash');
  late final _dart_isar_key_add_long_list_hash _isar_key_add_long_list_hash =
      _isar_key_add_long_list_hash_ptr
          .asFunction<_dart_isar_key_add_long_list_hash>();

  int isar_create_instance(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
    ffi.Pointer<ffi.Int8> name,
    ffi.Pointer<ffi.Int8> path,
    bool relaxed_durability,
    ffi.Pointer<ffi.Int8> schema_json,
  ) {
    return _isar_create_instance(
      isar,
      name,
      path,
      relaxed_durability ? 1 : 0,
      schema_json,
    );
  }

  late final _isar_create_instance_ptr =
      _lookup<ffi.NativeFunction<_c_isar_create_instance>>(
          'isar_create_instance');
  late final _dart_isar_create_instance _isar_create_instance =
      _isar_create_instance_ptr.asFunction<_dart_isar_create_instance>();

  void isar_create_instance_async(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
    ffi.Pointer<ffi.Int8> name,
    ffi.Pointer<ffi.Int8> path,
    bool relaxed_durability,
    ffi.Pointer<ffi.Int8> schema_json,
    int port,
  ) {
    return _isar_create_instance_async(
      isar,
      name,
      path,
      relaxed_durability ? 1 : 0,
      schema_json,
      port,
    );
  }

  late final _isar_create_instance_async_ptr =
      _lookup<ffi.NativeFunction<_c_isar_create_instance_async>>(
          'isar_create_instance_async');
  late final _dart_isar_create_instance_async _isar_create_instance_async =
      _isar_create_instance_async_ptr
          .asFunction<_dart_isar_create_instance_async>();

  bool isar_close_instance(
    ffi.Pointer<ffi.NativeType> isar,
    bool delete_from_disk,
  ) {
    return _isar_close_instance(
          isar,
          delete_from_disk ? 1 : 0,
        ) !=
        0;
  }

  late final _isar_close_instance_ptr =
      _lookup<ffi.NativeFunction<_c_isar_close_instance>>(
          'isar_close_instance');
  late final _dart_isar_close_instance _isar_close_instance =
      _isar_close_instance_ptr.asFunction<_dart_isar_close_instance>();

  int isar_get_collection(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
    int index,
  ) {
    return _isar_get_collection(
      isar,
      collection,
      index,
    );
  }

  late final _isar_get_collection_ptr =
      _lookup<ffi.NativeFunction<_c_isar_get_collection>>(
          'isar_get_collection');
  late final _dart_isar_get_collection _isar_get_collection =
      _isar_get_collection_ptr.asFunction<_dart_isar_get_collection>();

  int isar_get_static_size_and_offsets(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Uint32> offsets,
  ) {
    return _isar_get_static_size_and_offsets(
      collection,
      offsets,
    );
  }

  late final _isar_get_static_size_and_offsets_ptr =
      _lookup<ffi.NativeFunction<_c_isar_get_static_size_and_offsets>>(
          'isar_get_static_size_and_offsets');
  late final _dart_isar_get_static_size_and_offsets
      _isar_get_static_size_and_offsets = _isar_get_static_size_and_offsets_ptr
          .asFunction<_dart_isar_get_static_size_and_offsets>();

  int isar_link(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int link_id,
    int id,
    int target_id,
  ) {
    return _isar_link(
      collection,
      txn,
      link_id,
      id,
      target_id,
    );
  }

  late final _isar_link_ptr =
      _lookup<ffi.NativeFunction<_c_isar_link>>('isar_link');
  late final _dart_isar_link _isar_link =
      _isar_link_ptr.asFunction<_dart_isar_link>();

  int isar_link_unlink(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int link_id,
    int id,
    int target_id,
  ) {
    return _isar_link_unlink(
      collection,
      txn,
      link_id,
      id,
      target_id,
    );
  }

  late final _isar_link_unlink_ptr =
      _lookup<ffi.NativeFunction<_c_isar_link_unlink>>('isar_link_unlink');
  late final _dart_isar_link_unlink _isar_link_unlink =
      _isar_link_unlink_ptr.asFunction<_dart_isar_link_unlink>();

  int isar_link_unlink_all(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int link_id,
    int id,
  ) {
    return _isar_link_unlink_all(
      collection,
      txn,
      link_id,
      id,
    );
  }

  late final _isar_link_unlink_all_ptr =
      _lookup<ffi.NativeFunction<_c_isar_link_unlink_all>>(
          'isar_link_unlink_all');
  late final _dart_isar_link_unlink_all _isar_link_unlink_all =
      _isar_link_unlink_all_ptr.asFunction<_dart_isar_link_unlink_all>();

  int isar_link_update_all(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int link_id,
    int id,
    ffi.Pointer<ffi.Int64> ids,
    int link_count,
    int unlink_count,
    bool replace,
  ) {
    return _isar_link_update_all(
      collection,
      txn,
      link_id,
      id,
      ids,
      link_count,
      unlink_count,
      replace ? 1 : 0,
    );
  }

  late final _isar_link_update_all_ptr =
      _lookup<ffi.NativeFunction<_c_isar_link_update_all>>(
          'isar_link_update_all');
  late final _dart_isar_link_update_all _isar_link_update_all =
      _isar_link_update_all_ptr.asFunction<_dart_isar_link_update_all>();

  ffi.Pointer<ffi.NativeType> isar_qb_create(
    ffi.Pointer<ffi.NativeType> collection,
  ) {
    return _isar_qb_create(
      collection,
    );
  }

  late final _isar_qb_create_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_create>>('isar_qb_create');
  late final _dart_isar_qb_create _isar_qb_create =
      _isar_qb_create_ptr.asFunction<_dart_isar_qb_create>();

  int isar_qb_add_id_where_clause(
    ffi.Pointer<ffi.NativeType> builder,
    int start_id,
    int end_id,
  ) {
    return _isar_qb_add_id_where_clause(
      builder,
      start_id,
      end_id,
    );
  }

  late final _isar_qb_add_id_where_clause_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_add_id_where_clause>>(
          'isar_qb_add_id_where_clause');
  late final _dart_isar_qb_add_id_where_clause _isar_qb_add_id_where_clause =
      _isar_qb_add_id_where_clause_ptr
          .asFunction<_dart_isar_qb_add_id_where_clause>();

  int isar_qb_add_index_where_clause(
    ffi.Pointer<ffi.NativeType> builder,
    int index_id,
    ffi.Pointer<ffi.NativeType> start_key,
    bool include_start,
    ffi.Pointer<ffi.NativeType> end_key,
    bool include_end,
    bool skip_duplicates,
  ) {
    return _isar_qb_add_index_where_clause(
      builder,
      index_id,
      start_key,
      include_start ? 1 : 0,
      end_key,
      include_end ? 1 : 0,
      skip_duplicates ? 1 : 0,
    );
  }

  late final _isar_qb_add_index_where_clause_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_add_index_where_clause>>(
          'isar_qb_add_index_where_clause');
  late final _dart_isar_qb_add_index_where_clause
      _isar_qb_add_index_where_clause = _isar_qb_add_index_where_clause_ptr
          .asFunction<_dart_isar_qb_add_index_where_clause>();

  int isar_qb_add_link_where_clause(
    ffi.Pointer<ffi.NativeType> builder,
    ffi.Pointer<ffi.NativeType> source_collection,
    int link_id,
    int id,
  ) {
    return _isar_qb_add_link_where_clause(
      builder,
      source_collection,
      link_id,
      id,
    );
  }

  late final _isar_qb_add_link_where_clause_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_add_link_where_clause>>(
          'isar_qb_add_link_where_clause');
  late final _dart_isar_qb_add_link_where_clause
      _isar_qb_add_link_where_clause = _isar_qb_add_link_where_clause_ptr
          .asFunction<_dart_isar_qb_add_link_where_clause>();

  void isar_qb_set_filter(
    ffi.Pointer<ffi.NativeType> builder,
    ffi.Pointer<ffi.NativeType> filter,
  ) {
    return _isar_qb_set_filter(
      builder,
      filter,
    );
  }

  late final _isar_qb_set_filter_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_set_filter>>('isar_qb_set_filter');
  late final _dart_isar_qb_set_filter _isar_qb_set_filter =
      _isar_qb_set_filter_ptr.asFunction<_dart_isar_qb_set_filter>();

  int isar_qb_add_sort_by(
    ffi.Pointer<ffi.NativeType> builder,
    int property_id,
    bool asc,
  ) {
    return _isar_qb_add_sort_by(
      builder,
      property_id,
      asc ? 1 : 0,
    );
  }

  late final _isar_qb_add_sort_by_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_add_sort_by>>(
          'isar_qb_add_sort_by');
  late final _dart_isar_qb_add_sort_by _isar_qb_add_sort_by =
      _isar_qb_add_sort_by_ptr.asFunction<_dart_isar_qb_add_sort_by>();

  int isar_qb_add_distinct_by(
    ffi.Pointer<ffi.NativeType> builder,
    int property_id,
    bool case_sensitive,
  ) {
    return _isar_qb_add_distinct_by(
      builder,
      property_id,
      case_sensitive ? 1 : 0,
    );
  }

  late final _isar_qb_add_distinct_by_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_add_distinct_by>>(
          'isar_qb_add_distinct_by');
  late final _dart_isar_qb_add_distinct_by _isar_qb_add_distinct_by =
      _isar_qb_add_distinct_by_ptr.asFunction<_dart_isar_qb_add_distinct_by>();

  void isar_qb_set_offset_limit(
    ffi.Pointer<ffi.NativeType> builder,
    int offset,
    int limit,
  ) {
    return _isar_qb_set_offset_limit(
      builder,
      offset,
      limit,
    );
  }

  late final _isar_qb_set_offset_limit_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_set_offset_limit>>(
          'isar_qb_set_offset_limit');
  late final _dart_isar_qb_set_offset_limit _isar_qb_set_offset_limit =
      _isar_qb_set_offset_limit_ptr
          .asFunction<_dart_isar_qb_set_offset_limit>();

  ffi.Pointer<ffi.NativeType> isar_qb_build(
    ffi.Pointer<ffi.NativeType> builder,
  ) {
    return _isar_qb_build(
      builder,
    );
  }

  late final _isar_qb_build_ptr =
      _lookup<ffi.NativeFunction<_c_isar_qb_build>>('isar_qb_build');
  late final _dart_isar_qb_build _isar_qb_build =
      _isar_qb_build_ptr.asFunction<_dart_isar_qb_build>();

  void isar_q_free(
    ffi.Pointer<ffi.NativeType> query,
  ) {
    return _isar_q_free(
      query,
    );
  }

  late final _isar_q_free_ptr =
      _lookup<ffi.NativeFunction<_c_isar_q_free>>('isar_q_free');
  late final _dart_isar_q_free _isar_q_free =
      _isar_q_free_ptr.asFunction<_dart_isar_q_free>();

  int isar_q_find(
    ffi.Pointer<ffi.NativeType> query,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObjectSet> result,
    int limit,
  ) {
    return _isar_q_find(
      query,
      txn,
      result,
      limit,
    );
  }

  late final _isar_q_find_ptr =
      _lookup<ffi.NativeFunction<_c_isar_q_find>>('isar_q_find');
  late final _dart_isar_q_find _isar_q_find =
      _isar_q_find_ptr.asFunction<_dart_isar_q_find>();

  int isar_q_delete(
    ffi.Pointer<ffi.NativeType> query,
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    int limit,
    ffi.Pointer<ffi.Uint32> count,
  ) {
    return _isar_q_delete(
      query,
      collection,
      txn,
      limit,
      count,
    );
  }

  late final _isar_q_delete_ptr =
      _lookup<ffi.NativeFunction<_c_isar_q_delete>>('isar_q_delete');
  late final _dart_isar_q_delete _isar_q_delete =
      _isar_q_delete_ptr.asFunction<_dart_isar_q_delete>();

  int isar_q_export_json(
    ffi.Pointer<ffi.NativeType> query,
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<ffi.Int8> id_name,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>> json_bytes,
    ffi.Pointer<ffi.Uint32> json_length,
  ) {
    return _isar_q_export_json(
      query,
      collection,
      txn,
      id_name,
      json_bytes,
      json_length,
    );
  }

  late final _isar_q_export_json_ptr =
      _lookup<ffi.NativeFunction<_c_isar_q_export_json>>('isar_q_export_json');
  late final _dart_isar_q_export_json _isar_q_export_json =
      _isar_q_export_json_ptr.asFunction<_dart_isar_q_export_json>();

  void isar_free_json(
    ffi.Pointer<ffi.Uint8> json_bytes,
    int json_length,
  ) {
    return _isar_free_json(
      json_bytes,
      json_length,
    );
  }

  late final _isar_free_json_ptr =
      _lookup<ffi.NativeFunction<_c_isar_free_json>>('isar_free_json');
  late final _dart_isar_free_json _isar_free_json =
      _isar_free_json_ptr.asFunction<_dart_isar_free_json>();

  int isar_q_aggregate(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> query,
    ffi.Pointer<ffi.NativeType> txn,
    int operation,
    int property_id,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> result,
  ) {
    return _isar_q_aggregate(
      collection,
      query,
      txn,
      operation,
      property_id,
      result,
    );
  }

  late final _isar_q_aggregate_ptr =
      _lookup<ffi.NativeFunction<_c_isar_q_aggregate>>('isar_q_aggregate');
  late final _dart_isar_q_aggregate _isar_q_aggregate =
      _isar_q_aggregate_ptr.asFunction<_dart_isar_q_aggregate>();

  int isar_q_aggregate_long_result(
    ffi.Pointer<ffi.NativeType> result,
  ) {
    return _isar_q_aggregate_long_result(
      result,
    );
  }

  late final _isar_q_aggregate_long_result_ptr =
      _lookup<ffi.NativeFunction<_c_isar_q_aggregate_long_result>>(
          'isar_q_aggregate_long_result');
  late final _dart_isar_q_aggregate_long_result _isar_q_aggregate_long_result =
      _isar_q_aggregate_long_result_ptr
          .asFunction<_dart_isar_q_aggregate_long_result>();

  double isar_q_aggregate_double_result(
    ffi.Pointer<ffi.NativeType> result,
  ) {
    return _isar_q_aggregate_double_result(
      result,
    );
  }

  late final _isar_q_aggregate_double_result_ptr =
      _lookup<ffi.NativeFunction<_c_isar_q_aggregate_double_result>>(
          'isar_q_aggregate_double_result');
  late final _dart_isar_q_aggregate_double_result
      _isar_q_aggregate_double_result = _isar_q_aggregate_double_result_ptr
          .asFunction<_dart_isar_q_aggregate_double_result>();

  void isar_free_raw_obj_list(
    ffi.Pointer<RawObjectSet> ros,
  ) {
    return _isar_free_raw_obj_list(
      ros,
    );
  }

  late final _isar_free_raw_obj_list_ptr =
      _lookup<ffi.NativeFunction<_c_isar_free_raw_obj_list>>(
          'isar_free_raw_obj_list');
  late final _dart_isar_free_raw_obj_list _isar_free_raw_obj_list =
      _isar_free_raw_obj_list_ptr.asFunction<_dart_isar_free_raw_obj_list>();

  int isar_txn_begin(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
    bool sync_1,
    bool write,
    bool silent,
    int port,
  ) {
    return _isar_txn_begin(
      isar,
      txn,
      sync_1 ? 1 : 0,
      write ? 1 : 0,
      silent ? 1 : 0,
      port,
    );
  }

  late final _isar_txn_begin_ptr =
      _lookup<ffi.NativeFunction<_c_isar_txn_begin>>('isar_txn_begin');
  late final _dart_isar_txn_begin _isar_txn_begin =
      _isar_txn_begin_ptr.asFunction<_dart_isar_txn_begin>();

  int isar_txn_finish(
    ffi.Pointer<ffi.NativeType> txn,
    bool commit,
  ) {
    return _isar_txn_finish(
      txn,
      commit ? 1 : 0,
    );
  }

  late final _isar_txn_finish_ptr =
      _lookup<ffi.NativeFunction<_c_isar_txn_finish>>('isar_txn_finish');
  late final _dart_isar_txn_finish _isar_txn_finish =
      _isar_txn_finish_ptr.asFunction<_dart_isar_txn_finish>();

  ffi.Pointer<ffi.NativeType> isar_watch_collection(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.NativeType> collection,
    int port,
  ) {
    return _isar_watch_collection(
      isar,
      collection,
      port,
    );
  }

  late final _isar_watch_collection_ptr =
      _lookup<ffi.NativeFunction<_c_isar_watch_collection>>(
          'isar_watch_collection');
  late final _dart_isar_watch_collection _isar_watch_collection =
      _isar_watch_collection_ptr.asFunction<_dart_isar_watch_collection>();

  ffi.Pointer<ffi.NativeType> isar_watch_object(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.NativeType> collection,
    int id,
    int port,
  ) {
    return _isar_watch_object(
      isar,
      collection,
      id,
      port,
    );
  }

  late final _isar_watch_object_ptr =
      _lookup<ffi.NativeFunction<_c_isar_watch_object>>('isar_watch_object');
  late final _dart_isar_watch_object _isar_watch_object =
      _isar_watch_object_ptr.asFunction<_dart_isar_watch_object>();

  ffi.Pointer<ffi.NativeType> isar_watch_query(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> query,
    int port,
  ) {
    return _isar_watch_query(
      isar,
      collection,
      query,
      port,
    );
  }

  late final _isar_watch_query_ptr =
      _lookup<ffi.NativeFunction<_c_isar_watch_query>>('isar_watch_query');
  late final _dart_isar_watch_query _isar_watch_query =
      _isar_watch_query_ptr.asFunction<_dart_isar_watch_query>();

  void isar_stop_watching(
    ffi.Pointer<ffi.NativeType> handle,
  ) {
    return _isar_stop_watching(
      handle,
    );
  }

  late final _isar_stop_watching_ptr =
      _lookup<ffi.NativeFunction<_c_isar_stop_watching>>('isar_stop_watching');
  late final _dart_isar_stop_watching _isar_stop_watching =
      _isar_stop_watching_ptr.asFunction<_dart_isar_stop_watching>();
}

abstract class RawObject extends ffi.Struct {
  @ffi.Int64()
  external int id;

  external ffi.Pointer<ffi.Uint8> buffer;

  @ffi.Uint32()
  external int buffer_length;
}

class RawObjectSet extends ffi.Struct {
  external ffi.Pointer<RawObject> objects;

  @ffi.Uint32()
  external int length;
}

typedef _c_isar_find_word_boundaries = ffi.Pointer<ffi.Uint32> Function(
  ffi.Pointer<ffi.Uint8> input_bytes,
  ffi.Uint32 length,
  ffi.Pointer<ffi.Uint32> number_words,
);

typedef _dart_isar_find_word_boundaries = ffi.Pointer<ffi.Uint32> Function(
  ffi.Pointer<ffi.Uint8> input_bytes,
  int length,
  ffi.Pointer<ffi.Uint32> number_words,
);

typedef _c_isar_free_word_boundaries = ffi.Void Function(
  ffi.Pointer<ffi.Uint32> boundaries,
  ffi.Uint32 word_count,
);

typedef _dart_isar_free_word_boundaries = void Function(
  ffi.Pointer<ffi.Uint32> boundaries,
  int word_count,
);

typedef _c_isar_get_error = ffi.Pointer<ffi.Int8> Function(
  ffi.Int64 err_code,
);

typedef _dart_isar_get_error = ffi.Pointer<ffi.Int8> Function(
  int err_code,
);

typedef _c_isar_free_error = ffi.Void Function(
  ffi.Pointer<ffi.Int8> error,
);

typedef _dart_isar_free_error = void Function(
  ffi.Pointer<ffi.Int8> error,
);

typedef _c_isar_get = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_get = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_get_by_index = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 index_id,
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_get_by_index = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int index_id,
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_get_all = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> objects,
);

typedef _dart_isar_get_all = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> objects,
);

typedef _c_isar_get_all_by_index = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 index_id,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> keys,
  ffi.Pointer<RawObjectSet> objects,
);

typedef _dart_isar_get_all_by_index = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int index_id,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> keys,
  ffi.Pointer<RawObjectSet> objects,
);

typedef _c_isar_put = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
  ffi.Uint8 replace_on_conflict,
);

typedef _dart_isar_put = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
  int replace_on_conflict,
);

typedef _c_isar_put_all = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> objects,
  ffi.Uint8 replace_on_conflict,
);

typedef _dart_isar_put_all = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> objects,
  int replace_on_conflict,
);

typedef _c_isar_delete = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Int64 id,
  ffi.Pointer<ffi.Uint8> deleted,
);

typedef _dart_isar_delete = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int id,
  ffi.Pointer<ffi.Uint8> deleted,
);

typedef _c_isar_delete_by_index = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 index_id,
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Uint8> deleted,
);

typedef _dart_isar_delete_by_index = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int index_id,
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Uint8> deleted,
);

typedef _c_isar_delete_all = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<ffi.Int64> ids,
  ffi.Uint32 ids_length,
  ffi.Pointer<ffi.Uint32> count,
);

typedef _dart_isar_delete_all = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<ffi.Int64> ids,
  int ids_length,
  ffi.Pointer<ffi.Uint32> count,
);

typedef _c_isar_delete_all_by_index = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 index_id,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> keys,
  ffi.Uint32 keys_length,
  ffi.Pointer<ffi.Uint32> count,
);

typedef _dart_isar_delete_all_by_index = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int index_id,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> keys,
  int keys_length,
  ffi.Pointer<ffi.Uint32> count,
);

typedef _c_isar_clear = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _dart_isar_clear = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _c_isar_json_import = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<ffi.Int8> id_name,
  ffi.Pointer<ffi.Uint8> json_bytes,
  ffi.Uint32 json_length,
  ffi.Uint8 replace_on_conflict,
);

typedef _dart_isar_json_import = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<ffi.Int8> id_name,
  ffi.Pointer<ffi.Uint8> json_bytes,
  int json_length,
  int replace_on_conflict,
);

typedef DartPostCObjectFnType = ffi.Int8 Function(
  ffi.Int64,
  ffi.Pointer<ffi.Dart_CObject>,
);

typedef _c_isar_connect_dart_api = ffi.Void Function(
  ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> ptr,
);

typedef _dart_isar_connect_dart_api = void Function(
  ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnType>> ptr,
);

typedef _c_isar_filter_static = ffi.Void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint8 value,
);

typedef _dart_isar_filter_static = void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int value,
);

typedef _c_isar_filter_and_or = ffi.Void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint8 and,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> conditions,
  ffi.Uint32 length,
);

typedef _dart_isar_filter_and_or = void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int and,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> conditions,
  int length,
);

typedef _c_isar_filter_not = ffi.Void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.NativeType> condition,
);

typedef _dart_isar_filter_not = void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.NativeType> condition,
);

typedef _c_isar_filter_link = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.NativeType> condition,
  ffi.Uint32 link_id,
);

typedef _dart_isar_filter_link = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.NativeType> condition,
  int link_id,
);

typedef _c_isar_filter_null = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint32 property_id,
  ffi.Uint8 any_null,
);

typedef _dart_isar_filter_null = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int property_id,
  int any_null,
);

typedef _c_isar_filter_id = ffi.Int64 Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Int64 lower,
  ffi.Uint8 include_lower,
  ffi.Int64 upper,
  ffi.Uint8 include_upper,
);

typedef _dart_isar_filter_id = int Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int lower,
  int include_lower,
  int upper,
  int include_upper,
);

typedef _c_isar_filter_byte = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint8 lower,
  ffi.Uint8 include_lower,
  ffi.Uint8 upper,
  ffi.Uint8 include_upper,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_byte = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int lower,
  int include_lower,
  int upper,
  int include_upper,
  int property_id,
);

typedef _c_isar_filter_long = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Int64 lower,
  ffi.Uint8 include_lower,
  ffi.Int64 upper,
  ffi.Uint8 include_upper,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_long = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int lower,
  int include_lower,
  int upper,
  int include_upper,
  int property_id,
);

typedef _c_isar_filter_double = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Double lower,
  ffi.Double upper,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_double = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  double lower,
  double upper,
  int property_id,
);

typedef _c_isar_filter_string = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> lower,
  ffi.Uint8 include_lower,
  ffi.Pointer<ffi.Int8> upper,
  ffi.Uint8 include_upper,
  ffi.Uint8 case_sensitive,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_string = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> lower,
  int include_lower,
  ffi.Pointer<ffi.Int8> upper,
  int include_upper,
  int case_sensitive,
  int property_id,
);

typedef _c_isar_filter_string_starts_with = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  ffi.Uint8 case_sensitive,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_string_starts_with = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  int case_sensitive,
  int property_id,
);

typedef _c_isar_filter_string_ends_with = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  ffi.Uint8 case_sensitive,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_string_ends_with = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  int case_sensitive,
  int property_id,
);

typedef _c_isar_filter_string_contains = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  ffi.Uint8 case_sensitive,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_string_contains = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  int case_sensitive,
  int property_id,
);

typedef _c_isar_filter_string_matches = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  ffi.Uint8 case_sensitive,
  ffi.Uint32 property_id,
);

typedef _dart_isar_filter_string_matches = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Pointer<ffi.Int8> value,
  int case_sensitive,
  int property_id,
);

typedef _c_isar_key_create = ffi.Void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> key,
);

typedef _dart_isar_key_create = void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> key,
);

typedef _c_isar_key_add_byte = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Uint8 value,
);

typedef _dart_isar_key_add_byte = void Function(
  ffi.Pointer<ffi.NativeType> key,
  int value,
);

typedef _c_isar_key_add_int = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Int32 value,
);

typedef _dart_isar_key_add_int = void Function(
  ffi.Pointer<ffi.NativeType> key,
  int value,
);

typedef _c_isar_key_add_long = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Int64 value,
);

typedef _dart_isar_key_add_long = void Function(
  ffi.Pointer<ffi.NativeType> key,
  int value,
);

typedef _c_isar_key_add_float = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Float value,
);

typedef _dart_isar_key_add_float = void Function(
  ffi.Pointer<ffi.NativeType> key,
  double value,
);

typedef _c_isar_key_add_double = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Double value,
);

typedef _dart_isar_key_add_double = void Function(
  ffi.Pointer<ffi.NativeType> key,
  double value,
);

typedef _c_isar_key_add_string = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int8> value,
  ffi.Uint8 case_sensitive,
);

typedef _dart_isar_key_add_string = void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int8> value,
  int case_sensitive,
);

typedef _c_isar_key_add_string_hash = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int8> value,
  ffi.Uint8 case_sensitive,
);

typedef _dart_isar_key_add_string_hash = void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int8> value,
  int case_sensitive,
);

typedef _c_isar_key_add_string_list_hash = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> value,
  ffi.Uint32 length,
  ffi.Uint8 case_sensitive,
);

typedef _dart_isar_key_add_string_list_hash = void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> value,
  int length,
  int case_sensitive,
);

typedef _c_isar_key_add_byte_list_hash = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Uint8> value,
  ffi.Uint32 length,
);

typedef _dart_isar_key_add_byte_list_hash = void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Uint8> value,
  int length,
);

typedef _c_isar_key_add_int_list_hash = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int32> value,
  ffi.Uint32 length,
);

typedef _dart_isar_key_add_int_list_hash = void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int32> value,
  int length,
);

typedef _c_isar_key_add_long_list_hash = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int64> value,
  ffi.Uint32 length,
);

typedef _dart_isar_key_add_long_list_hash = void Function(
  ffi.Pointer<ffi.NativeType> key,
  ffi.Pointer<ffi.Int64> value,
  int length,
);

typedef _c_isar_create_instance = ffi.Int64 Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
  ffi.Pointer<ffi.Int8> name,
  ffi.Pointer<ffi.Int8> path,
  ffi.Uint8 relaxed_durability,
  ffi.Pointer<ffi.Int8> schema_json,
);

typedef _dart_isar_create_instance = int Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
  ffi.Pointer<ffi.Int8> name,
  ffi.Pointer<ffi.Int8> path,
  int relaxed_durability,
  ffi.Pointer<ffi.Int8> schema_json,
);

typedef _c_isar_create_instance_async = ffi.Void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
  ffi.Pointer<ffi.Int8> name,
  ffi.Pointer<ffi.Int8> path,
  ffi.Uint8 relaxed_durability,
  ffi.Pointer<ffi.Int8> schema_json,
  ffi.Int64 port,
);

typedef _dart_isar_create_instance_async = void Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
  ffi.Pointer<ffi.Int8> name,
  ffi.Pointer<ffi.Int8> path,
  int relaxed_durability,
  ffi.Pointer<ffi.Int8> schema_json,
  int port,
);

typedef _c_isar_close_instance = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Uint8 delete_from_disk,
);

typedef _dart_isar_close_instance = int Function(
  ffi.Pointer<ffi.NativeType> isar,
  int delete_from_disk,
);

typedef _c_isar_get_collection = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
  ffi.Uint32 index,
);

typedef _dart_isar_get_collection = int Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
  int index,
);

typedef _c_isar_get_static_size_and_offsets = ffi.Uint32 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Uint32> offsets,
);

typedef _dart_isar_get_static_size_and_offsets = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Uint32> offsets,
);

typedef _c_isar_link = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 link_id,
  ffi.Int64 id,
  ffi.Int64 target_id,
);

typedef _dart_isar_link = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int link_id,
  int id,
  int target_id,
);

typedef _c_isar_link_unlink = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 link_id,
  ffi.Int64 id,
  ffi.Int64 target_id,
);

typedef _dart_isar_link_unlink = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int link_id,
  int id,
  int target_id,
);

typedef _c_isar_link_unlink_all = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 link_id,
  ffi.Int64 id,
);

typedef _dart_isar_link_unlink_all = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int link_id,
  int id,
);

typedef _c_isar_link_update_all = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 link_id,
  ffi.Int64 id,
  ffi.Pointer<ffi.Int64> ids,
  ffi.Uint32 link_count,
  ffi.Uint32 unlink_count,
  ffi.Uint8 replace,
);

typedef _dart_isar_link_update_all = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int link_id,
  int id,
  ffi.Pointer<ffi.Int64> ids,
  int link_count,
  int unlink_count,
  int replace,
);

typedef _c_isar_qb_create = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> collection,
);

typedef _dart_isar_qb_create = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> collection,
);

typedef _c_isar_qb_add_id_where_clause = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Int64 start_id,
  ffi.Int64 end_id,
);

typedef _dart_isar_qb_add_id_where_clause = int Function(
  ffi.Pointer<ffi.NativeType> builder,
  int start_id,
  int end_id,
);

typedef _c_isar_qb_add_index_where_clause = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Uint32 index_id,
  ffi.Pointer<ffi.NativeType> start_key,
  ffi.Uint8 include_start,
  ffi.Pointer<ffi.NativeType> end_key,
  ffi.Uint8 include_end,
  ffi.Uint8 skip_duplicates,
);

typedef _dart_isar_qb_add_index_where_clause = int Function(
  ffi.Pointer<ffi.NativeType> builder,
  int index_id,
  ffi.Pointer<ffi.NativeType> start_key,
  int include_start,
  ffi.Pointer<ffi.NativeType> end_key,
  int include_end,
  int skip_duplicates,
);

typedef _c_isar_qb_add_link_where_clause = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> source_collection,
  ffi.Uint32 link_id,
  ffi.Int64 id,
);

typedef _dart_isar_qb_add_link_where_clause = int Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> source_collection,
  int link_id,
  int id,
);

typedef _c_isar_qb_set_filter = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> filter,
);

typedef _dart_isar_qb_set_filter = void Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> filter,
);

typedef _c_isar_qb_add_sort_by = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Uint32 property_id,
  ffi.Uint8 asc,
);

typedef _dart_isar_qb_add_sort_by = int Function(
  ffi.Pointer<ffi.NativeType> builder,
  int property_id,
  int asc,
);

typedef _c_isar_qb_add_distinct_by = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Uint32 property_id,
  ffi.Uint8 case_sensitive,
);

typedef _dart_isar_qb_add_distinct_by = int Function(
  ffi.Pointer<ffi.NativeType> builder,
  int property_id,
  int case_sensitive,
);

typedef _c_isar_qb_set_offset_limit = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Int64 offset,
  ffi.Int64 limit,
);

typedef _dart_isar_qb_set_offset_limit = void Function(
  ffi.Pointer<ffi.NativeType> builder,
  int offset,
  int limit,
);

typedef _c_isar_qb_build = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> builder,
);

typedef _dart_isar_qb_build = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> builder,
);

typedef _c_isar_q_free = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> query,
);

typedef _dart_isar_q_free = void Function(
  ffi.Pointer<ffi.NativeType> query,
);

typedef _c_isar_q_find = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> result,
  ffi.Uint32 limit,
);

typedef _dart_isar_q_find = int Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> result,
  int limit,
);

typedef _c_isar_q_delete = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint32 limit,
  ffi.Pointer<ffi.Uint32> count,
);

typedef _dart_isar_q_delete = int Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  int limit,
  ffi.Pointer<ffi.Uint32> count,
);

typedef _c_isar_q_export_json = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<ffi.Int8> id_name,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> json_bytes,
  ffi.Pointer<ffi.Uint32> json_length,
);

typedef _dart_isar_q_export_json = int Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<ffi.Int8> id_name,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> json_bytes,
  ffi.Pointer<ffi.Uint32> json_length,
);

typedef _c_isar_free_json = ffi.Void Function(
  ffi.Pointer<ffi.Uint8> json_bytes,
  ffi.Uint32 json_length,
);

typedef _dart_isar_free_json = void Function(
  ffi.Pointer<ffi.Uint8> json_bytes,
  int json_length,
);

typedef _c_isar_q_aggregate = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint8 operation,
  ffi.Uint32 property_id,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> result,
);

typedef _dart_isar_q_aggregate = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> txn,
  int operation,
  int property_id,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> result,
);

typedef _c_isar_q_aggregate_long_result = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> result,
);

typedef _dart_isar_q_aggregate_long_result = int Function(
  ffi.Pointer<ffi.NativeType> result,
);

typedef _c_isar_q_aggregate_double_result = ffi.Double Function(
  ffi.Pointer<ffi.NativeType> result,
);

typedef _dart_isar_q_aggregate_double_result = double Function(
  ffi.Pointer<ffi.NativeType> result,
);

typedef _c_isar_free_raw_obj_list = ffi.Void Function(
  ffi.Pointer<RawObjectSet> ros,
);

typedef _dart_isar_free_raw_obj_list = void Function(
  ffi.Pointer<RawObjectSet> ros,
);

typedef _c_isar_txn_begin = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
  ffi.Uint8 sync_1,
  ffi.Uint8 write,
  ffi.Uint8 silent,
  ffi.Int64 port,
);

typedef _dart_isar_txn_begin = int Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
  int sync_1,
  int write,
  int silent,
  int port,
);

typedef _c_isar_txn_finish = ffi.Int64 Function(
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Uint8 commit,
);

typedef _dart_isar_txn_finish = int Function(
  ffi.Pointer<ffi.NativeType> txn,
  int commit,
);

typedef _c_isar_watch_collection = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Int64 port,
);

typedef _dart_isar_watch_collection = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
  int port,
);

typedef _c_isar_watch_object = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Int64 id,
  ffi.Int64 port,
);

typedef _dart_isar_watch_object = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
  int id,
  int port,
);

typedef _c_isar_watch_query = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> query,
  ffi.Int64 port,
);

typedef _dart_isar_watch_query = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> query,
  int port,
);

typedef _c_isar_stop_watching = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> handle,
);

typedef _dart_isar_stop_watching = void Function(
  ffi.Pointer<ffi.NativeType> handle,
);
