// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

class IsarCoreBindings {
  /// Holds the Dynamic library.
  final ffi.DynamicLibrary _dylib;

  /// The symbols are looked up in [dynamicLibrary].
  IsarCoreBindings(ffi.DynamicLibrary dynamicLibrary) : _dylib = dynamicLibrary;

  int isar_get(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObject> object,
  ) {
    _isar_get ??=
        _dylib.lookupFunction<_c_isar_get, _dart_isar_get>('isar_get');
    return _isar_get(
      collection,
      txn,
      object,
    );
  }

  _dart_isar_get _isar_get;

  void isar_get_async(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObject> object,
  ) {
    _isar_get_async ??=
        _dylib.lookupFunction<_c_isar_get_async, _dart_isar_get_async>(
            'isar_get_async');
    return _isar_get_async(
      collection,
      txn,
      object,
    );
  }

  _dart_isar_get_async _isar_get_async;

  int isar_put(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObject> object,
  ) {
    _isar_put ??=
        _dylib.lookupFunction<_c_isar_put, _dart_isar_put>('isar_put');
    return _isar_put(
      collection,
      txn,
      object,
    );
  }

  _dart_isar_put _isar_put;

  void isar_put_async(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObject> object,
  ) {
    _isar_put_async ??=
        _dylib.lookupFunction<_c_isar_put_async, _dart_isar_put_async>(
            'isar_put_async');
    return _isar_put_async(
      collection,
      txn,
      object,
    );
  }

  _dart_isar_put_async _isar_put_async;

  int isar_delete(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObject> object,
  ) {
    _isar_delete ??=
        _dylib.lookupFunction<_c_isar_delete, _dart_isar_delete>('isar_delete');
    return _isar_delete(
      collection,
      txn,
      object,
    );
  }

  _dart_isar_delete _isar_delete;

  int isar_clear(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.NativeType> txn,
  ) {
    _isar_clear ??=
        _dylib.lookupFunction<_c_isar_clear, _dart_isar_clear>('isar_clear');
    return _isar_clear(
      collection,
      txn,
    );
  }

  _dart_isar_clear _isar_clear;

  int isar_filter_and_or(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    bool and,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> conditions,
    int length,
  ) {
    _isar_filter_and_or ??=
        _dylib.lookupFunction<_c_isar_filter_and_or, _dart_isar_filter_and_or>(
            'isar_filter_and_or');
    return _isar_filter_and_or(
      filter,
      and ? 1 : 0,
      conditions,
      length,
    );
  }

  _dart_isar_filter_and_or _isar_filter_and_or;

  int isar_filter_is_null(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    bool is_null,
    int property_index,
  ) {
    _isar_filter_is_null ??= _dylib.lookupFunction<_c_isar_filter_is_null,
        _dart_isar_filter_is_null>('isar_filter_is_null');
    return _isar_filter_is_null(
      collection,
      filter,
      is_null ? 1 : 0,
      property_index,
    );
  }

  _dart_isar_filter_is_null _isar_filter_is_null;

  int isar_filter_byte_between(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int lower,
    bool include_lower,
    int upper,
    bool include_upper,
    int property_index,
  ) {
    _isar_filter_byte_between ??= _dylib.lookupFunction<
        _c_isar_filter_byte_between,
        _dart_isar_filter_byte_between>('isar_filter_byte_between');
    return _isar_filter_byte_between(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      property_index,
    );
  }

  _dart_isar_filter_byte_between _isar_filter_byte_between;

  int isar_filter_int_between(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int lower,
    bool include_lower,
    int upper,
    bool include_upper,
    int property_index,
  ) {
    _isar_filter_int_between ??= _dylib.lookupFunction<
        _c_isar_filter_int_between,
        _dart_isar_filter_int_between>('isar_filter_int_between');
    return _isar_filter_int_between(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      property_index,
    );
  }

  _dart_isar_filter_int_between _isar_filter_int_between;

  int isar_filter_float_between(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    double lower,
    bool include_lower,
    double upper,
    bool include_upper,
    int property_index,
  ) {
    _isar_filter_float_between ??= _dylib.lookupFunction<
        _c_isar_filter_float_between,
        _dart_isar_filter_float_between>('isar_filter_float_between');
    return _isar_filter_float_between(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      property_index,
    );
  }

  _dart_isar_filter_float_between _isar_filter_float_between;

  int isar_filter_long_between(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int lower,
    bool include_lower,
    int upper,
    bool include_upper,
    int property_index,
  ) {
    _isar_filter_long_between ??= _dylib.lookupFunction<
        _c_isar_filter_long_between,
        _dart_isar_filter_long_between>('isar_filter_long_between');
    return _isar_filter_long_between(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      property_index,
    );
  }

  _dart_isar_filter_long_between _isar_filter_long_between;

  int isar_filter_double_between(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    double lower,
    bool include_lower,
    double upper,
    bool include_upper,
    int property_index,
  ) {
    _isar_filter_double_between ??= _dylib.lookupFunction<
        _c_isar_filter_double_between,
        _dart_isar_filter_double_between>('isar_filter_double_between');
    return _isar_filter_double_between(
      collection,
      filter,
      lower,
      include_lower ? 1 : 0,
      upper,
      include_upper ? 1 : 0,
      property_index,
    );
  }

  _dart_isar_filter_double_between _isar_filter_double_between;

  int isar_filter_byte_not_equal(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int value,
    int property_index,
  ) {
    _isar_filter_byte_not_equal ??= _dylib.lookupFunction<
        _c_isar_filter_byte_not_equal,
        _dart_isar_filter_byte_not_equal>('isar_filter_byte_not_equal');
    return _isar_filter_byte_not_equal(
      collection,
      filter,
      value,
      property_index,
    );
  }

  _dart_isar_filter_byte_not_equal _isar_filter_byte_not_equal;

  int isar_filter_int_not_equal(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int value,
    int property_index,
  ) {
    _isar_filter_int_not_equal ??= _dylib.lookupFunction<
        _c_isar_filter_int_not_equal,
        _dart_isar_filter_int_not_equal>('isar_filter_int_not_equal');
    return _isar_filter_int_not_equal(
      collection,
      filter,
      value,
      property_index,
    );
  }

  _dart_isar_filter_int_not_equal _isar_filter_int_not_equal;

  int isar_filter_float_not_equal(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    double value,
    int property_index,
  ) {
    _isar_filter_float_not_equal ??= _dylib.lookupFunction<
        _c_isar_filter_float_not_equal,
        _dart_isar_filter_float_not_equal>('isar_filter_float_not_equal');
    return _isar_filter_float_not_equal(
      collection,
      filter,
      value,
      property_index,
    );
  }

  _dart_isar_filter_float_not_equal _isar_filter_float_not_equal;

  int isar_filter_long_not_equal(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    int value,
    int property_index,
  ) {
    _isar_filter_long_not_equal ??= _dylib.lookupFunction<
        _c_isar_filter_long_not_equal,
        _dart_isar_filter_long_not_equal>('isar_filter_long_not_equal');
    return _isar_filter_long_not_equal(
      collection,
      filter,
      value,
      property_index,
    );
  }

  _dart_isar_filter_long_not_equal _isar_filter_long_not_equal;

  int isar_filter_double_not_equal(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
    double value,
    int property_index,
  ) {
    _isar_filter_double_not_equal ??= _dylib.lookupFunction<
        _c_isar_filter_double_not_equal,
        _dart_isar_filter_double_not_equal>('isar_filter_double_not_equal');
    return _isar_filter_double_not_equal(
      collection,
      filter,
      value,
      property_index,
    );
  }

  _dart_isar_filter_double_not_equal _isar_filter_double_not_equal;

  int isar_create_instance(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
    ffi.Pointer<ffi.Int8> path,
    int max_size,
    ffi.Pointer<ffi.NativeType> schema,
  ) {
    _isar_create_instance ??= _dylib.lookupFunction<_c_isar_create_instance,
        _dart_isar_create_instance>('isar_create_instance');
    return _isar_create_instance(
      isar,
      path,
      max_size,
      schema,
    );
  }

  _dart_isar_create_instance _isar_create_instance;

  int isar_get_collection(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
    int index,
  ) {
    _isar_get_collection ??= _dylib.lookupFunction<_c_isar_get_collection,
        _dart_isar_get_collection>('isar_get_collection');
    return _isar_get_collection(
      isar,
      collection,
      index,
    );
  }

  _dart_isar_get_collection _isar_get_collection;

  ffi.Pointer<ffi.NativeType> isar_qb_create(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.NativeType> collection,
  ) {
    _isar_qb_create ??=
        _dylib.lookupFunction<_c_isar_qb_create, _dart_isar_qb_create>(
            'isar_qb_create');
    return _isar_qb_create(
      isar,
      collection,
    );
  }

  _dart_isar_qb_create _isar_qb_create;

  void isar_qb_add_where_clause(
    ffi.Pointer<ffi.NativeType> builder,
    ffi.Pointer<ffi.NativeType> where_clause,
    bool include_lower,
    bool include_upper,
  ) {
    _isar_qb_add_where_clause ??= _dylib.lookupFunction<
        _c_isar_qb_add_where_clause,
        _dart_isar_qb_add_where_clause>('isar_qb_add_where_clause');
    return _isar_qb_add_where_clause(
      builder,
      where_clause,
      include_lower ? 1 : 0,
      include_upper ? 1 : 0,
    );
  }

  _dart_isar_qb_add_where_clause _isar_qb_add_where_clause;

  void isar_qb_set_filter(
    ffi.Pointer<ffi.NativeType> builder,
    ffi.Pointer<ffi.NativeType> filter,
  ) {
    _isar_qb_set_filter ??=
        _dylib.lookupFunction<_c_isar_qb_set_filter, _dart_isar_qb_set_filter>(
            'isar_qb_set_filter');
    return _isar_qb_set_filter(
      builder,
      filter,
    );
  }

  _dart_isar_qb_set_filter _isar_qb_set_filter;

  ffi.Pointer<ffi.NativeType> isar_qb_build(
    ffi.Pointer<ffi.NativeType> builder,
  ) {
    _isar_qb_build ??= _dylib
        .lookupFunction<_c_isar_qb_build, _dart_isar_qb_build>('isar_qb_build');
    return _isar_qb_build(
      builder,
    );
  }

  _dart_isar_qb_build _isar_qb_build;

  int isar_q_find_all(
    ffi.Pointer<ffi.NativeType> query,
    ffi.Pointer<ffi.NativeType> txn,
    ffi.Pointer<RawObjectSet> result,
  ) {
    _isar_q_find_all ??=
        _dylib.lookupFunction<_c_isar_q_find_all, _dart_isar_q_find_all>(
            'isar_q_find_all');
    return _isar_q_find_all(
      query,
      txn,
      result,
    );
  }

  _dart_isar_q_find_all _isar_q_find_all;

  ffi.Pointer<RawObject> isar_alloc_raw_obj(
    int size,
  ) {
    _isar_alloc_raw_obj ??=
        _dylib.lookupFunction<_c_isar_alloc_raw_obj, _dart_isar_alloc_raw_obj>(
            'isar_alloc_raw_obj');
    return _isar_alloc_raw_obj(
      size,
    );
  }

  _dart_isar_alloc_raw_obj _isar_alloc_raw_obj;

  void isar_free_raw_obj(
    ffi.Pointer<RawObject> object,
  ) {
    _isar_free_raw_obj ??=
        _dylib.lookupFunction<_c_isar_free_raw_obj, _dart_isar_free_raw_obj>(
            'isar_free_raw_obj');
    return _isar_free_raw_obj(
      object,
    );
  }

  _dart_isar_free_raw_obj _isar_free_raw_obj;

  ffi.Pointer<ffi.NativeType> isar_schema_create() {
    _isar_schema_create ??=
        _dylib.lookupFunction<_c_isar_schema_create, _dart_isar_schema_create>(
            'isar_schema_create');
    return _isar_schema_create();
  }

  _dart_isar_schema_create _isar_schema_create;

  int isar_schema_create_collection(
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
    ffi.Pointer<ffi.Int8> name,
  ) {
    _isar_schema_create_collection ??= _dylib.lookupFunction<
        _c_isar_schema_create_collection,
        _dart_isar_schema_create_collection>('isar_schema_create_collection');
    return _isar_schema_create_collection(
      collection,
      name,
    );
  }

  _dart_isar_schema_create_collection _isar_schema_create_collection;

  int isar_schema_add_collection(
    ffi.Pointer<ffi.NativeType> schema,
    ffi.Pointer<ffi.NativeType> collection,
  ) {
    _isar_schema_add_collection ??= _dylib.lookupFunction<
        _c_isar_schema_add_collection,
        _dart_isar_schema_add_collection>('isar_schema_add_collection');
    return _isar_schema_add_collection(
      schema,
      collection,
    );
  }

  _dart_isar_schema_add_collection _isar_schema_add_collection;

  int isar_schema_add_property(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Int8> name,
    int data_type,
  ) {
    _isar_schema_add_property ??= _dylib.lookupFunction<
        _c_isar_schema_add_property,
        _dart_isar_schema_add_property>('isar_schema_add_property');
    return _isar_schema_add_property(
      collection,
      name,
      data_type,
    );
  }

  _dart_isar_schema_add_property _isar_schema_add_property;

  int isar_schema_add_index(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.Int8>> property_names,
    int property_names_length,
    bool unique,
    bool hash_value,
  ) {
    _isar_schema_add_index ??= _dylib.lookupFunction<_c_isar_schema_add_index,
        _dart_isar_schema_add_index>('isar_schema_add_index');
    return _isar_schema_add_index(
      collection,
      property_names,
      property_names_length,
      unique ? 1 : 0,
      hash_value ? 1 : 0,
    );
  }

  _dart_isar_schema_add_index _isar_schema_add_index;

  int isar_txn_begin(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
    bool write,
  ) {
    _isar_txn_begin ??=
        _dylib.lookupFunction<_c_isar_txn_begin, _dart_isar_txn_begin>(
            'isar_txn_begin');
    return _isar_txn_begin(
      isar,
      txn,
      write ? 1 : 0,
    );
  }

  _dart_isar_txn_begin _isar_txn_begin;

  void isar_txn_begin_async(
    ffi.Pointer<ffi.NativeType> isar,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
    bool write,
    int handle,
  ) {
    _isar_txn_begin_async ??= _dylib.lookupFunction<_c_isar_txn_begin_async,
        _dart_isar_txn_begin_async>('isar_txn_begin_async');
    return _isar_txn_begin_async(
      isar,
      txn,
      write ? 1 : 0,
      handle,
    );
  }

  _dart_isar_txn_begin_async _isar_txn_begin_async;

  int isar_txn_commit(
    ffi.Pointer<ffi.NativeType> txn,
  ) {
    _isar_txn_commit ??=
        _dylib.lookupFunction<_c_isar_txn_commit, _dart_isar_txn_commit>(
            'isar_txn_commit');
    return _isar_txn_commit(
      txn,
    );
  }

  _dart_isar_txn_commit _isar_txn_commit;

  void isar_txn_commit_async(
    ffi.Pointer<ffi.NativeType> txn,
  ) {
    _isar_txn_commit_async ??= _dylib.lookupFunction<_c_isar_txn_commit_async,
        _dart_isar_txn_commit_async>('isar_txn_commit_async');
    return _isar_txn_commit_async(
      txn,
    );
  }

  _dart_isar_txn_commit_async _isar_txn_commit_async;

  int isar_txn_abort(
    ffi.Pointer<ffi.NativeType> txn,
  ) {
    _isar_txn_abort ??=
        _dylib.lookupFunction<_c_isar_txn_abort, _dart_isar_txn_abort>(
            'isar_txn_abort');
    return _isar_txn_abort(
      txn,
    );
  }

  _dart_isar_txn_abort _isar_txn_abort;

  void isar_txn_abort_async(
    ffi.Pointer<ffi.NativeType> txn,
  ) {
    _isar_txn_abort_async ??= _dylib.lookupFunction<_c_isar_txn_abort_async,
        _dart_isar_txn_abort_async>('isar_txn_abort_async');
    return _isar_txn_abort_async(
      txn,
    );
  }

  _dart_isar_txn_abort_async _isar_txn_abort_async;

  int isar_wc_create(
    ffi.Pointer<ffi.NativeType> collection,
    ffi.Pointer<ffi.Pointer<ffi.NativeType>> wc,
    bool primary,
    int index_index,
  ) {
    _isar_wc_create ??=
        _dylib.lookupFunction<_c_isar_wc_create, _dart_isar_wc_create>(
            'isar_wc_create');
    return _isar_wc_create(
      collection,
      wc,
      primary ? 1 : 0,
      index_index,
    );
  }

  _dart_isar_wc_create _isar_wc_create;

  int isar_wc_oid(
    ffi.Pointer<ffi.NativeType> where_clause,
    int time,
    int rand_counter,
  ) {
    _isar_wc_oid ??=
        _dylib.lookupFunction<_c_isar_wc_oid, _dart_isar_wc_oid>('isar_wc_oid');
    return _isar_wc_oid(
      where_clause,
      time,
      rand_counter,
    );
  }

  _dart_isar_wc_oid _isar_wc_oid;

  void isar_wc_add_oid_time(
    ffi.Pointer<ffi.NativeType> where_clause,
    int lower,
    int upper,
  ) {
    _isar_wc_add_oid_time ??= _dylib.lookupFunction<_c_isar_wc_add_oid_time,
        _dart_isar_wc_add_oid_time>('isar_wc_add_oid_time');
    return _isar_wc_add_oid_time(
      where_clause,
      lower,
      upper,
    );
  }

  _dart_isar_wc_add_oid_time _isar_wc_add_oid_time;

  void isar_wc_add_byte(
    ffi.Pointer<ffi.NativeType> where_clause,
    int lower,
    int upper,
  ) {
    _isar_wc_add_byte ??=
        _dylib.lookupFunction<_c_isar_wc_add_byte, _dart_isar_wc_add_byte>(
            'isar_wc_add_byte');
    return _isar_wc_add_byte(
      where_clause,
      lower,
      upper,
    );
  }

  _dart_isar_wc_add_byte _isar_wc_add_byte;

  void isar_wc_add_int(
    ffi.Pointer<ffi.NativeType> where_clause,
    int lower,
    int upper,
  ) {
    _isar_wc_add_int ??=
        _dylib.lookupFunction<_c_isar_wc_add_int, _dart_isar_wc_add_int>(
            'isar_wc_add_int');
    return _isar_wc_add_int(
      where_clause,
      lower,
      upper,
    );
  }

  _dart_isar_wc_add_int _isar_wc_add_int;

  void isar_wc_add_float(
    ffi.Pointer<ffi.NativeType> where_clause,
    double lower,
    double upper,
  ) {
    _isar_wc_add_float ??=
        _dylib.lookupFunction<_c_isar_wc_add_float, _dart_isar_wc_add_float>(
            'isar_wc_add_float');
    return _isar_wc_add_float(
      where_clause,
      lower,
      upper,
    );
  }

  _dart_isar_wc_add_float _isar_wc_add_float;

  void isar_wc_add_long(
    ffi.Pointer<ffi.NativeType> where_clause,
    int lower,
    int upper,
  ) {
    _isar_wc_add_long ??=
        _dylib.lookupFunction<_c_isar_wc_add_long, _dart_isar_wc_add_long>(
            'isar_wc_add_long');
    return _isar_wc_add_long(
      where_clause,
      lower,
      upper,
    );
  }

  _dart_isar_wc_add_long _isar_wc_add_long;

  void isar_wc_add_double(
    ffi.Pointer<ffi.NativeType> where_clause,
    double lower,
    double upper,
  ) {
    _isar_wc_add_double ??=
        _dylib.lookupFunction<_c_isar_wc_add_double, _dart_isar_wc_add_double>(
            'isar_wc_add_double');
    return _isar_wc_add_double(
      where_clause,
      lower,
      upper,
    );
  }

  _dart_isar_wc_add_double _isar_wc_add_double;

  void isar_wc_add_string_hash(
    ffi.Pointer<ffi.NativeType> where_clause,
    ffi.Pointer<ffi.Int8> value,
  ) {
    _isar_wc_add_string_hash ??= _dylib.lookupFunction<
        _c_isar_wc_add_string_hash,
        _dart_isar_wc_add_string_hash>('isar_wc_add_string_hash');
    return _isar_wc_add_string_hash(
      where_clause,
      value,
    );
  }

  _dart_isar_wc_add_string_hash _isar_wc_add_string_hash;

  void isar_wc_add_string_value(
    ffi.Pointer<ffi.NativeType> where_clause,
    ffi.Pointer<ffi.Int8> lower,
    ffi.Pointer<ffi.Int8> upper,
  ) {
    _isar_wc_add_string_value ??= _dylib.lookupFunction<
        _c_isar_wc_add_string_value,
        _dart_isar_wc_add_string_value>('isar_wc_add_string_value');
    return _isar_wc_add_string_value(
      where_clause,
      lower,
      upper,
    );
  }

  _dart_isar_wc_add_string_value _isar_wc_add_string_value;
}

abstract class RawObject extends ffi.Struct {
  @ffi.Uint32()
  int oid_time;

  @ffi.Uint64()
  int oid_rand_counter;

  ffi.Pointer<ffi.Uint8> data;

  @ffi.Uint32()
  int data_length;
}

class RawObjectSet extends ffi.Struct {
  ffi.Pointer<RawObject> objects;

  @ffi.Uint32()
  int length;
}

typedef _c_isar_get = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_get = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_get_async = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_get_async = void Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_put = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_put = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_put_async = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_put_async = void Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_delete = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_delete = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_clear = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _dart_isar_clear = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _c_isar_filter_and_or = ffi.Uint8 Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint8 and,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> conditions,
  ffi.Uint32 length,
);

typedef _dart_isar_filter_and_or = int Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int and,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> conditions,
  int length,
);

typedef _c_isar_filter_is_null = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint8 is_null,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_is_null = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int is_null,
  int property_index,
);

typedef _c_isar_filter_byte_between = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint8 lower,
  ffi.Uint8 include_lower,
  ffi.Uint8 upper,
  ffi.Uint8 include_upper,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_byte_between = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int lower,
  int include_lower,
  int upper,
  int include_upper,
  int property_index,
);

typedef _c_isar_filter_int_between = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Int32 lower,
  ffi.Uint8 include_lower,
  ffi.Int32 upper,
  ffi.Uint8 include_upper,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_int_between = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int lower,
  int include_lower,
  int upper,
  int include_upper,
  int property_index,
);

typedef _c_isar_filter_float_between = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Float lower,
  ffi.Uint8 include_lower,
  ffi.Float upper,
  ffi.Uint8 include_upper,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_float_between = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  double lower,
  int include_lower,
  double upper,
  int include_upper,
  int property_index,
);

typedef _c_isar_filter_long_between = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Int64 lower,
  ffi.Uint8 include_lower,
  ffi.Int64 upper,
  ffi.Uint8 include_upper,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_long_between = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int lower,
  int include_lower,
  int upper,
  int include_upper,
  int property_index,
);

typedef _c_isar_filter_double_between = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Double lower,
  ffi.Uint8 include_lower,
  ffi.Double upper,
  ffi.Uint8 include_upper,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_double_between = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  double lower,
  int include_lower,
  double upper,
  int include_upper,
  int property_index,
);

typedef _c_isar_filter_byte_not_equal = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Uint8 value,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_byte_not_equal = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int value,
  int property_index,
);

typedef _c_isar_filter_int_not_equal = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Int32 value,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_int_not_equal = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int value,
  int property_index,
);

typedef _c_isar_filter_float_not_equal = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Float value,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_float_not_equal = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  double value,
  int property_index,
);

typedef _c_isar_filter_long_not_equal = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Int64 value,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_long_not_equal = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  int value,
  int property_index,
);

typedef _c_isar_filter_double_not_equal = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  ffi.Double value,
  ffi.Uint32 property_index,
);

typedef _dart_isar_filter_double_not_equal = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> filter,
  double value,
  int property_index,
);

typedef _c_isar_create_instance = ffi.Uint8 Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
  ffi.Pointer<ffi.Int8> path,
  ffi.Uint32 max_size,
  ffi.Pointer<ffi.NativeType> schema,
);

typedef _dart_isar_create_instance = int Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> isar,
  ffi.Pointer<ffi.Int8> path,
  int max_size,
  ffi.Pointer<ffi.NativeType> schema,
);

typedef _c_isar_get_collection = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
  ffi.Uint32 index,
);

typedef _dart_isar_get_collection = int Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
  int index,
);

typedef _c_isar_qb_create = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
);

typedef _dart_isar_qb_create = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.NativeType> collection,
);

typedef _c_isar_qb_add_where_clause = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Uint8 include_lower,
  ffi.Uint8 include_upper,
);

typedef _dart_isar_qb_add_where_clause = void Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> where_clause,
  int include_lower,
  int include_upper,
);

typedef _c_isar_qb_set_filter = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> filter,
);

typedef _dart_isar_qb_set_filter = void Function(
  ffi.Pointer<ffi.NativeType> builder,
  ffi.Pointer<ffi.NativeType> filter,
);

typedef _c_isar_qb_build = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> builder,
);

typedef _dart_isar_qb_build = ffi.Pointer<ffi.NativeType> Function(
  ffi.Pointer<ffi.NativeType> builder,
);

typedef _c_isar_q_find_all = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> result,
);

typedef _dart_isar_q_find_all = int Function(
  ffi.Pointer<ffi.NativeType> query,
  ffi.Pointer<ffi.NativeType> txn,
  ffi.Pointer<RawObjectSet> result,
);

typedef _c_isar_alloc_raw_obj = ffi.Pointer<RawObject> Function(
  ffi.Uint32 size,
);

typedef _dart_isar_alloc_raw_obj = ffi.Pointer<RawObject> Function(
  int size,
);

typedef _c_isar_free_raw_obj = ffi.Void Function(
  ffi.Pointer<RawObject> object,
);

typedef _dart_isar_free_raw_obj = void Function(
  ffi.Pointer<RawObject> object,
);

typedef _c_isar_schema_create = ffi.Pointer<ffi.NativeType> Function();

typedef _dart_isar_schema_create = ffi.Pointer<ffi.NativeType> Function();

typedef _c_isar_schema_create_collection = ffi.Uint8 Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
  ffi.Pointer<ffi.Int8> name,
);

typedef _dart_isar_schema_create_collection = int Function(
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> collection,
  ffi.Pointer<ffi.Int8> name,
);

typedef _c_isar_schema_add_collection = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> schema,
  ffi.Pointer<ffi.NativeType> collection,
);

typedef _dart_isar_schema_add_collection = int Function(
  ffi.Pointer<ffi.NativeType> schema,
  ffi.Pointer<ffi.NativeType> collection,
);

typedef _c_isar_schema_add_property = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Int8> name,
  ffi.Uint8 data_type,
);

typedef _dart_isar_schema_add_property = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Int8> name,
  int data_type,
);

typedef _c_isar_schema_add_index = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> property_names,
  ffi.Uint32 property_names_length,
  ffi.Uint8 unique,
  ffi.Uint8 hash_value,
);

typedef _dart_isar_schema_add_index = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.Int8>> property_names,
  int property_names_length,
  int unique,
  int hash_value,
);

typedef _c_isar_txn_begin = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
  ffi.Uint8 write,
);

typedef _dart_isar_txn_begin = int Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
  int write,
);

typedef _c_isar_txn_begin_async = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
  ffi.Uint8 write,
  ffi.Int64 handle,
);

typedef _dart_isar_txn_begin_async = void Function(
  ffi.Pointer<ffi.NativeType> isar,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> txn,
  int write,
  int handle,
);

typedef _c_isar_txn_commit = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _dart_isar_txn_commit = int Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _c_isar_txn_commit_async = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _dart_isar_txn_commit_async = void Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _c_isar_txn_abort = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _dart_isar_txn_abort = int Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _c_isar_txn_abort_async = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _dart_isar_txn_abort_async = void Function(
  ffi.Pointer<ffi.NativeType> txn,
);

typedef _c_isar_wc_create = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> wc,
  ffi.Uint8 primary,
  ffi.Uint32 index_index,
);

typedef _dart_isar_wc_create = int Function(
  ffi.Pointer<ffi.NativeType> collection,
  ffi.Pointer<ffi.Pointer<ffi.NativeType>> wc,
  int primary,
  int index_index,
);

typedef _c_isar_wc_oid = ffi.Uint8 Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Uint32 time,
  ffi.Uint64 rand_counter,
);

typedef _dart_isar_wc_oid = int Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  int time,
  int rand_counter,
);

typedef _c_isar_wc_add_oid_time = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Uint32 lower,
  ffi.Uint32 upper,
);

typedef _dart_isar_wc_add_oid_time = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  int lower,
  int upper,
);

typedef _c_isar_wc_add_byte = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Uint8 lower,
  ffi.Uint8 upper,
);

typedef _dart_isar_wc_add_byte = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  int lower,
  int upper,
);

typedef _c_isar_wc_add_int = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Int32 lower,
  ffi.Int32 upper,
);

typedef _dart_isar_wc_add_int = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  int lower,
  int upper,
);

typedef _c_isar_wc_add_float = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Float lower,
  ffi.Float upper,
);

typedef _dart_isar_wc_add_float = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  double lower,
  double upper,
);

typedef _c_isar_wc_add_long = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Int64 lower,
  ffi.Int64 upper,
);

typedef _dart_isar_wc_add_long = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  int lower,
  int upper,
);

typedef _c_isar_wc_add_double = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Double lower,
  ffi.Double upper,
);

typedef _dart_isar_wc_add_double = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  double lower,
  double upper,
);

typedef _c_isar_wc_add_string_hash = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Pointer<ffi.Int8> value,
);

typedef _dart_isar_wc_add_string_hash = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Pointer<ffi.Int8> value,
);

typedef _c_isar_wc_add_string_value = ffi.Void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Pointer<ffi.Int8> lower,
  ffi.Pointer<ffi.Int8> upper,
);

typedef _dart_isar_wc_add_string_value = void Function(
  ffi.Pointer<ffi.NativeType> where_clause,
  ffi.Pointer<ffi.Int8> lower,
  ffi.Pointer<ffi.Int8> upper,
);
